import sqlite3
conn = sqlite3.connect('data/manager_ai.db')
c = conn.cursor()
c.execute("SELECT * FROM settings WHERE key LIKE '%queue%' OR key = 'auto_process' OR key = 'work_queue_paused'")
rows = c.fetchall()
print('Settings:', rows)
c.execute("SELECT * FROM queue_entries ORDER BY created_at DESC LIMIT 10")
entries = c.fetchall()
print('Queue entries:', entries)
conn.close()
