"""add terminal_id to agent_step_runs

Revision ID: 072a542ac08c
Revises: f75dc9e9f3ff
Create Date: 2026-05-21 18:08:23.808323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '072a542ac08c'
down_revision: Union[str, None] = 'f75dc9e9f3ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
