"""remove declined state and decline_feedback column

Revision ID: 3a10ffbc3944
Revises: f6a7b8c9d0e1
Create Date: 2026-03-22 13:01:33.593793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a10ffbc3944'
down_revision: Union[str, None] = 'f6a7b8c9d0e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Migrate any DECLINED issues to PLANNED before removing the status
    op.execute("UPDATE issues SET status = 'Planned' WHERE status = 'Declined'")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('NEW', 'REASONING', 'PLANNED', 'ACCEPTED', 'FINISHED', 'CANCELED', name='issuestatus'),
               existing_nullable=False)
        batch_op.drop_column('decline_feedback')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('decline_feedback', sa.TEXT(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.Enum('NEW', 'REASONING', 'PLANNED', 'ACCEPTED', 'FINISHED', 'CANCELED', name='issuestatus'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)

    # ### end Alembic commands ###
