"""add finished_at to issues

Revision ID: 5922b9fdc87a
Revises: 04d6489a8fd4
Create Date: 2026-05-27 15:39:10.934531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5922b9fdc87a'
down_revision: Union[str, None] = '04d6489a8fd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
