"""add embedding_status to files and issues

Revision ID: 8768ea9ac530
Revises: 9feeba5d9d85
Create Date: 2026-04-17 13:39:53.328993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8768ea9ac530'
down_revision: Union[str, None] = '9feeba5d9d85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding_status', sa.String(length=20), nullable=False, server_default='pending'))
        batch_op.add_column(sa.Column('embedding_error', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('embedding_updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('project_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding_status', sa.String(length=20), nullable=False, server_default='pending'))
        batch_op.add_column(sa.Column('embedding_error', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('embedding_updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_files', schema=None) as batch_op:
        batch_op.drop_column('embedding_updated_at')
        batch_op.drop_column('embedding_error')
        batch_op.drop_column('embedding_status')

    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_column('embedding_updated_at')
        batch_op.drop_column('embedding_error')
        batch_op.drop_column('embedding_status')

    # ### end Alembic commands ###
