"""add project url and reindex memories

Revision ID: d41b6753e00d
Revises: 57caaadbd338
Create Date: 2026-05-04 10:55:08.506906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd41b6753e00d'
down_revision: Union[str, None] = '57caaadbd338'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.drop_index('ix_memories_parent')
        batch_op.drop_index('ix_memories_project')
        batch_op.create_index(batch_op.f('ix_memories_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memories_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('memory_links', schema=None) as batch_op:
        batch_op.drop_index('ix_memory_links_to')
        batch_op.create_index(batch_op.f('ix_memory_links_to_id'), ['to_id'], unique=False)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=2000), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('url')

    with op.batch_alter_table('memory_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memory_links_to_id'))
        batch_op.create_index('ix_memory_links_to', ['to_id'], unique=False)

    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memories_project_id'))
        batch_op.drop_index(batch_op.f('ix_memories_parent_id'))
        batch_op.create_index('ix_memories_project', ['project_id'], unique=False)
        batch_op.create_index('ix_memories_parent', ['parent_id'], unique=False)

    # ### end Alembic commands ###
